# Generated by Django 5.1.6 on 2025-02-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeGenerator', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
